name: CI with Earthly

on:
  push:
    branches: ['main']

jobs:
  test-and-deploy:
    runs-on: ubicloud-standard-2-arm
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      FORCE_COLOR: 1
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.8.3
      - uses: actions/checkout@v2
      - name: Test
        run: earthly --org orgname --sat xs-sat --ci +test
      - name: Deploy
        run: earthly --org orgname --sat xs-sat --ci +deploy
